# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
reference_sum <- function(x) {
    .Call(`_RustPkg_reference_sum`, x)
}

#' @export
ffi_sum <- function(x) {
    .Call(`_RustPkg_ffi_sum`, x)
}

